spring.datasource.url=jdbc:postgresql://localhost:5432/pma-springbootdb
spring.datasource.username=postgres
spring.datasource.password=password

spring.sql.init.mode=never
#above property makes sure application will not load dummy data from data.sql if set to never
#if set to always it will run data.sql and schema.sql will be loaded everytime you run app

spring.jpa.hibernate.ddl-auto=none
#this will make sure db is not created based on java code when set to none
#when you are running this project for the first time then set this to create

spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

spring.jpa.show-sql=true
spring.thymeleaf.cache=false

#version=${envVersionNum} // this is reading from environment variable - eclipse, linux, windows, prod profile, uat
version=3.0.0